[tools]
go = "1.26.3"
air = "latest"
golangci-lint = "latest"
actionlint = "latest"
"go:golang.org/x/tools/cmd/gonew" = "latest"
atlas = "latest"
ripgrep = "latest"
fd = "latest"
sd = "latest"
gitleaks = "latest"
pnpm = "latest"
"npm:concurrently" = "latest"

[settings]
npm.package_manager = "pnpm"

[env]
_.file = ".env"
