services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lfiber:local
    container_name: lfiber
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./.env.production:/app/.env:ro
    networks:
      - backend

networks:
  backend:
    external: true
