app:
  name: ${APP_NAME:Fiber Starter}
  env: ${APP_ENV:local}
  debug: ${APP_DEBUG:false}
  port: ${APP_PORT:8080}
  host: 0.0.0.0
  timezone: ${APP_TIMEZONE:UTC}
  locale: ${APP_LOCALE:zh-CN}
  url: ${APP_URL:http://localhost:8080}
  fiber:
    prefork: false
    body_limit: 4194304
    concurrency: 262144
    read_buffer_size: 16384
    read_timeout: 30
    write_timeout: 30
    idle_timeout: 120
    trust_proxy: false
    proxy_header: X-Forwarded-For
    stream_request_body: false
    immutable: false
