app:
  name: ${APP_NAME:Fiber Starter}
  env: ${APP_ENV:development}
  debug: ${APP_DEBUG:true}
  port: ${APP_PORT:8080}
  host: ${APP_HOST:0.0.0.0}
  timezone: ${APP_TIMEZONE:UTC}
  url: ${APP_URL:http://localhost:8080}
  fiber:
    prefork: ${APP_FIBER_PREFORK:false}
    server_header: ${APP_FIBER_SERVER_HEADER:""}
    body_limit: ${APP_FIBER_BODY_LIMIT:4194304}
    concurrency: ${APP_FIBER_CONCURRENCY:262144}
    read_buffer_size: ${APP_FIBER_READ_BUFFER_SIZE:16384}
    read_timeout: ${APP_FIBER_READ_TIMEOUT:30}
    write_timeout: ${APP_FIBER_WRITE_TIMEOUT:30}
    idle_timeout: ${APP_FIBER_IDLE_TIMEOUT:120}
    trust_proxy: ${APP_FIBER_TRUST_PROXY:false}
    proxy_header: ${APP_FIBER_PROXY_HEADER:X-Forwarded-For}
    stream_request_body: ${APP_FIBER_STREAM_REQUEST_BODY:false}
    immutable: ${APP_FIBER_IMMUTABLE:false}
