storage:
  disk: ${FILESYSTEM_DISK:local}
  local:
    root: ./storage/app
    url: /storage
  public:
    root: ./storage/app/public
    url: /storage/public
  s3:
    key: ${AWS_ACCESS_KEY_ID:""}
    secret: ${AWS_SECRET_ACCESS_KEY:""}
    region: ${AWS_DEFAULT_REGION:us-east-1}
    bucket: ${AWS_BUCKET:""}
    endpoint: ${AWS_ENDPOINT:""}
    use_path_style: true
