-- Create "users" table
CREATE TABLE "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" character varying(255) NOT NULL,
  "email" character varying(255) NOT NULL,
  "password" character varying(255) NOT NULL,
  "avatar" character varying(500) NULL,
  "phone" character varying(20) NULL,
  "status" character varying(20) NOT NULL DEFAULT 'active',
  "email_verified_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" timestamptz NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "ck_users_status" CHECK (status IN ('active','inactive','banned'))
);
-- Create index "idx_users_email" to table: "users"
CREATE UNIQUE INDEX "idx_users_email" ON "users" ("email");
-- Create index "idx_users_status" to table: "users"
CREATE INDEX "idx_users_status" ON "users" ("status");
-- Create index "idx_users_deleted_at" to table: "users"
CREATE INDEX "idx_users_deleted_at" ON "users" ("deleted_at");
