-- Create "auth_otps" table
CREATE TABLE "auth_otps" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" character varying(255) NOT NULL,
  "purpose" character varying(32) NOT NULL,
  "code_hash" character varying(255) NOT NULL,
  "expires_at" timestamptz NOT NULL,
  "sent_at" timestamptz NOT NULL,
  "attempts" integer NOT NULL DEFAULT 0,
  "max_attempts" integer NOT NULL DEFAULT 5,
  "consumed_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id"),
  CONSTRAINT "ck_auth_otps_purpose" CHECK (purpose IN ('signup','password_reset')),
  CONSTRAINT "ck_auth_otps_attempts" CHECK (attempts >= 0),
  CONSTRAINT "ck_auth_otps_max_attempts" CHECK (max_attempts > 0)
);
-- Create index "idx_auth_otps_email_purpose_created_at" to table: "auth_otps"
CREATE INDEX "idx_auth_otps_email_purpose_created_at" ON "auth_otps" ("email", "purpose", "created_at" DESC);
-- Create index "idx_auth_otps_expires_at" to table: "auth_otps"
CREATE INDEX "idx_auth_otps_expires_at" ON "auth_otps" ("expires_at");
