// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mailmocks

import (
	"lfiber/internal/providers/mail/contracts"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMailer
func (_mock *MockMailer) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMailer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMailer_Expecter) Close() *MockMailer_Close_Call {
	return &MockMailer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMailer_Close_Call) Run(run func()) *MockMailer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailer_Close_Call) Return(err error) *MockMailer_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_Close_Call) RunAndReturn(run func() error) *MockMailer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function for the type MockMailer
func (_mock *MockMailer) HealthCheck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockMailer_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
func (_e *MockMailer_Expecter) HealthCheck() *MockMailer_HealthCheck_Call {
	return &MockMailer_HealthCheck_Call{Call: _e.mock.On("HealthCheck")}
}

func (_c *MockMailer_HealthCheck_Call) Run(run func()) *MockMailer_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMailer_HealthCheck_Call) Return(err error) *MockMailer_HealthCheck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_HealthCheck_Call) RunAndReturn(run func() error) *MockMailer_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// Raw provides a mock function for the type MockMailer
func (_mock *MockMailer) Raw(to string, subject string, body string) error {
	ret := _mock.Called(to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for Raw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = returnFunc(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_Raw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Raw'
type MockMailer_Raw_Call struct {
	*mock.Call
}

// Raw is a helper method to define mock.On call
//   - to string
//   - subject string
//   - body string
func (_e *MockMailer_Expecter) Raw(to interface{}, subject interface{}, body interface{}) *MockMailer_Raw_Call {
	return &MockMailer_Raw_Call{Call: _e.mock.On("Raw", to, subject, body)}
}

func (_c *MockMailer_Raw_Call) Run(run func(to string, subject string, body string)) *MockMailer_Raw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMailer_Raw_Call) Return(err error) *MockMailer_Raw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_Raw_Call) RunAndReturn(run func(to string, subject string, body string) error) *MockMailer_Raw_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockMailer
func (_mock *MockMailer) Send(message contracts.Message) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(contracts.Message) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMailer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockMailer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - message contracts.Message
func (_e *MockMailer_Expecter) Send(message interface{}) *MockMailer_Send_Call {
	return &MockMailer_Send_Call{Call: _e.mock.On("Send", message)}
}

func (_c *MockMailer_Send_Call) Run(run func(message contracts.Message)) *MockMailer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 contracts.Message
		if args[0] != nil {
			arg0 = args[0].(contracts.Message)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMailer_Send_Call) Return(err error) *MockMailer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMailer_Send_Call) RunAndReturn(run func(message contracts.Message) error) *MockMailer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// To provides a mock function for the type MockMailer
func (_mock *MockMailer) To(to ...string) contracts.Message {
	var tmpRet mock.Arguments
	if len(to) > 0 {
		tmpRet = _mock.Called(to)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for To")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(...string) contracts.Message); ok {
		r0 = returnFunc(to...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMailer_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type MockMailer_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
//   - to ...string
func (_e *MockMailer_Expecter) To(to ...interface{}) *MockMailer_To_Call {
	return &MockMailer_To_Call{Call: _e.mock.On("To",
		append([]interface{}{}, to...)...)}
}

func (_c *MockMailer_To_Call) Run(run func(to ...string)) *MockMailer_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockMailer_To_Call) Return(message contracts.Message) *MockMailer_To_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMailer_To_Call) RunAndReturn(run func(to ...string) contracts.Message) *MockMailer_To_Call {
	_c.Call.Return(run)
	return _c
}
