// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mailmocks

import (
	"lfiber/internal/providers/mail/contracts"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessage creates a new instance of MockMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessage {
	mock := &MockMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessage is an autogenerated mock type for the Message type
type MockMessage struct {
	mock.Mock
}

type MockMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessage) EXPECT() *MockMessage_Expecter {
	return &MockMessage_Expecter{mock: &_m.Mock}
}

// Attach provides a mock function for the type MockMessage
func (_mock *MockMessage) Attach(filePath string) contracts.Message {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(string) contracts.Message); ok {
		r0 = returnFunc(filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type MockMessage_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - filePath string
func (_e *MockMessage_Expecter) Attach(filePath interface{}) *MockMessage_Attach_Call {
	return &MockMessage_Attach_Call{Call: _e.mock.On("Attach", filePath)}
}

func (_c *MockMessage_Attach_Call) Run(run func(filePath string)) *MockMessage_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Attach_Call) Return(message contracts.Message) *MockMessage_Attach_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Attach_Call) RunAndReturn(run func(filePath string) contracts.Message) *MockMessage_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// Bcc provides a mock function for the type MockMessage
func (_mock *MockMessage) Bcc(bcc ...string) contracts.Message {
	var tmpRet mock.Arguments
	if len(bcc) > 0 {
		tmpRet = _mock.Called(bcc)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Bcc")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(...string) contracts.Message); ok {
		r0 = returnFunc(bcc...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Bcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bcc'
type MockMessage_Bcc_Call struct {
	*mock.Call
}

// Bcc is a helper method to define mock.On call
//   - bcc ...string
func (_e *MockMessage_Expecter) Bcc(bcc ...interface{}) *MockMessage_Bcc_Call {
	return &MockMessage_Bcc_Call{Call: _e.mock.On("Bcc",
		append([]interface{}{}, bcc...)...)}
}

func (_c *MockMessage_Bcc_Call) Run(run func(bcc ...string)) *MockMessage_Bcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockMessage_Bcc_Call) Return(message contracts.Message) *MockMessage_Bcc_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Bcc_Call) RunAndReturn(run func(bcc ...string) contracts.Message) *MockMessage_Bcc_Call {
	_c.Call.Return(run)
	return _c
}

// Cc provides a mock function for the type MockMessage
func (_mock *MockMessage) Cc(cc ...string) contracts.Message {
	var tmpRet mock.Arguments
	if len(cc) > 0 {
		tmpRet = _mock.Called(cc)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Cc")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(...string) contracts.Message); ok {
		r0 = returnFunc(cc...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Cc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cc'
type MockMessage_Cc_Call struct {
	*mock.Call
}

// Cc is a helper method to define mock.On call
//   - cc ...string
func (_e *MockMessage_Expecter) Cc(cc ...interface{}) *MockMessage_Cc_Call {
	return &MockMessage_Cc_Call{Call: _e.mock.On("Cc",
		append([]interface{}{}, cc...)...)}
}

func (_c *MockMessage_Cc_Call) Run(run func(cc ...string)) *MockMessage_Cc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockMessage_Cc_Call) Return(message contracts.Message) *MockMessage_Cc_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Cc_Call) RunAndReturn(run func(cc ...string) contracts.Message) *MockMessage_Cc_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function for the type MockMessage
func (_mock *MockMessage) Data(data map[string]interface{}) contracts.Message {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) contracts.Message); ok {
		r0 = returnFunc(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockMessage_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
//   - data map[string]interface{}
func (_e *MockMessage_Expecter) Data(data interface{}) *MockMessage_Data_Call {
	return &MockMessage_Data_Call{Call: _e.mock.On("Data", data)}
}

func (_c *MockMessage_Data_Call) Run(run func(data map[string]interface{})) *MockMessage_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Data_Call) Return(message contracts.Message) *MockMessage_Data_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Data_Call) RunAndReturn(run func(data map[string]interface{}) contracts.Message) *MockMessage_Data_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachments provides a mock function for the type MockMessage
func (_mock *MockMessage) GetAttachments() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAttachments")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMessage_GetAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachments'
type MockMessage_GetAttachments_Call struct {
	*mock.Call
}

// GetAttachments is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetAttachments() *MockMessage_GetAttachments_Call {
	return &MockMessage_GetAttachments_Call{Call: _e.mock.On("GetAttachments")}
}

func (_c *MockMessage_GetAttachments_Call) Run(run func()) *MockMessage_GetAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetAttachments_Call) Return(strings []string) *MockMessage_GetAttachments_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMessage_GetAttachments_Call) RunAndReturn(run func() []string) *MockMessage_GetAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// GetBcc provides a mock function for the type MockMessage
func (_mock *MockMessage) GetBcc() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBcc")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMessage_GetBcc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBcc'
type MockMessage_GetBcc_Call struct {
	*mock.Call
}

// GetBcc is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetBcc() *MockMessage_GetBcc_Call {
	return &MockMessage_GetBcc_Call{Call: _e.mock.On("GetBcc")}
}

func (_c *MockMessage_GetBcc_Call) Run(run func()) *MockMessage_GetBcc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetBcc_Call) Return(strings []string) *MockMessage_GetBcc_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMessage_GetBcc_Call) RunAndReturn(run func() []string) *MockMessage_GetBcc_Call {
	_c.Call.Return(run)
	return _c
}

// GetBody provides a mock function for the type MockMessage
func (_mock *MockMessage) GetBody() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBody")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessage_GetBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBody'
type MockMessage_GetBody_Call struct {
	*mock.Call
}

// GetBody is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetBody() *MockMessage_GetBody_Call {
	return &MockMessage_GetBody_Call{Call: _e.mock.On("GetBody")}
}

func (_c *MockMessage_GetBody_Call) Run(run func()) *MockMessage_GetBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetBody_Call) Return(s string) *MockMessage_GetBody_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessage_GetBody_Call) RunAndReturn(run func() string) *MockMessage_GetBody_Call {
	_c.Call.Return(run)
	return _c
}

// GetCc provides a mock function for the type MockMessage
func (_mock *MockMessage) GetCc() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCc")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMessage_GetCc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCc'
type MockMessage_GetCc_Call struct {
	*mock.Call
}

// GetCc is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetCc() *MockMessage_GetCc_Call {
	return &MockMessage_GetCc_Call{Call: _e.mock.On("GetCc")}
}

func (_c *MockMessage_GetCc_Call) Run(run func()) *MockMessage_GetCc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetCc_Call) Return(strings []string) *MockMessage_GetCc_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMessage_GetCc_Call) RunAndReturn(run func() []string) *MockMessage_GetCc_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type MockMessage
func (_mock *MockMessage) GetData() map[string]interface{} {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 map[string]interface{}
	if returnFunc, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}
	return r0
}

// MockMessage_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type MockMessage_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetData() *MockMessage_GetData_Call {
	return &MockMessage_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *MockMessage_GetData_Call) Run(run func()) *MockMessage_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetData_Call) Return(stringToIfaceVal map[string]interface{}) *MockMessage_GetData_Call {
	_c.Call.Return(stringToIfaceVal)
	return _c
}

func (_c *MockMessage_GetData_Call) RunAndReturn(run func() map[string]interface{}) *MockMessage_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubject provides a mock function for the type MockMessage
func (_mock *MockMessage) GetSubject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSubject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessage_GetSubject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubject'
type MockMessage_GetSubject_Call struct {
	*mock.Call
}

// GetSubject is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetSubject() *MockMessage_GetSubject_Call {
	return &MockMessage_GetSubject_Call{Call: _e.mock.On("GetSubject")}
}

func (_c *MockMessage_GetSubject_Call) Run(run func()) *MockMessage_GetSubject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetSubject_Call) Return(s string) *MockMessage_GetSubject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessage_GetSubject_Call) RunAndReturn(run func() string) *MockMessage_GetSubject_Call {
	_c.Call.Return(run)
	return _c
}

// GetTo provides a mock function for the type MockMessage
func (_mock *MockMessage) GetTo() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTo")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockMessage_GetTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTo'
type MockMessage_GetTo_Call struct {
	*mock.Call
}

// GetTo is a helper method to define mock.On call
func (_e *MockMessage_Expecter) GetTo() *MockMessage_GetTo_Call {
	return &MockMessage_GetTo_Call{Call: _e.mock.On("GetTo")}
}

func (_c *MockMessage_GetTo_Call) Run(run func()) *MockMessage_GetTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_GetTo_Call) Return(strings []string) *MockMessage_GetTo_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockMessage_GetTo_Call) RunAndReturn(run func() []string) *MockMessage_GetTo_Call {
	_c.Call.Return(run)
	return _c
}

// Html provides a mock function for the type MockMessage
func (_mock *MockMessage) Html(body string) contracts.Message {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Html")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(string) contracts.Message); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Html_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Html'
type MockMessage_Html_Call struct {
	*mock.Call
}

// Html is a helper method to define mock.On call
//   - body string
func (_e *MockMessage_Expecter) Html(body interface{}) *MockMessage_Html_Call {
	return &MockMessage_Html_Call{Call: _e.mock.On("Html", body)}
}

func (_c *MockMessage_Html_Call) Run(run func(body string)) *MockMessage_Html_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Html_Call) Return(message contracts.Message) *MockMessage_Html_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Html_Call) RunAndReturn(run func(body string) contracts.Message) *MockMessage_Html_Call {
	_c.Call.Return(run)
	return _c
}

// IsHtml provides a mock function for the type MockMessage
func (_mock *MockMessage) IsHtml() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHtml")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockMessage_IsHtml_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHtml'
type MockMessage_IsHtml_Call struct {
	*mock.Call
}

// IsHtml is a helper method to define mock.On call
func (_e *MockMessage_Expecter) IsHtml() *MockMessage_IsHtml_Call {
	return &MockMessage_IsHtml_Call{Call: _e.mock.On("IsHtml")}
}

func (_c *MockMessage_IsHtml_Call) Run(run func()) *MockMessage_IsHtml_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_IsHtml_Call) Return(b bool) *MockMessage_IsHtml_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockMessage_IsHtml_Call) RunAndReturn(run func() bool) *MockMessage_IsHtml_Call {
	_c.Call.Return(run)
	return _c
}

// Mailable provides a mock function for the type MockMessage
func (_mock *MockMessage) Mailable(m contracts.Mailable) contracts.Message {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Mailable")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(contracts.Mailable) contracts.Message); ok {
		r0 = returnFunc(m)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Mailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mailable'
type MockMessage_Mailable_Call struct {
	*mock.Call
}

// Mailable is a helper method to define mock.On call
//   - m contracts.Mailable
func (_e *MockMessage_Expecter) Mailable(m interface{}) *MockMessage_Mailable_Call {
	return &MockMessage_Mailable_Call{Call: _e.mock.On("Mailable", m)}
}

func (_c *MockMessage_Mailable_Call) Run(run func(m contracts.Mailable)) *MockMessage_Mailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 contracts.Mailable
		if args[0] != nil {
			arg0 = args[0].(contracts.Mailable)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Mailable_Call) Return(message contracts.Message) *MockMessage_Mailable_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Mailable_Call) RunAndReturn(run func(m contracts.Mailable) contracts.Message) *MockMessage_Mailable_Call {
	_c.Call.Return(run)
	return _c
}

// Plain provides a mock function for the type MockMessage
func (_mock *MockMessage) Plain(body string) contracts.Message {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for Plain")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(string) contracts.Message); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Plain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Plain'
type MockMessage_Plain_Call struct {
	*mock.Call
}

// Plain is a helper method to define mock.On call
//   - body string
func (_e *MockMessage_Expecter) Plain(body interface{}) *MockMessage_Plain_Call {
	return &MockMessage_Plain_Call{Call: _e.mock.On("Plain", body)}
}

func (_c *MockMessage_Plain_Call) Run(run func(body string)) *MockMessage_Plain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Plain_Call) Return(message contracts.Message) *MockMessage_Plain_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Plain_Call) RunAndReturn(run func(body string) contracts.Message) *MockMessage_Plain_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockMessage
func (_mock *MockMessage) Subject(subject string) contracts.Message {
	ret := _mock.Called(subject)

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(string) contracts.Message); ok {
		r0 = returnFunc(subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
//   - subject string
func (_e *MockMessage_Expecter) Subject(subject interface{}) *MockMessage_Subject_Call {
	return &MockMessage_Subject_Call{Call: _e.mock.On("Subject", subject)}
}

func (_c *MockMessage_Subject_Call) Run(run func(subject string)) *MockMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessage_Subject_Call) Return(message contracts.Message) *MockMessage_Subject_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_Subject_Call) RunAndReturn(run func(subject string) contracts.Message) *MockMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}

// To provides a mock function for the type MockMessage
func (_mock *MockMessage) To(to ...string) contracts.Message {
	var tmpRet mock.Arguments
	if len(to) > 0 {
		tmpRet = _mock.Called(to)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for To")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(...string) contracts.Message); ok {
		r0 = returnFunc(to...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_To_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'To'
type MockMessage_To_Call struct {
	*mock.Call
}

// To is a helper method to define mock.On call
//   - to ...string
func (_e *MockMessage_Expecter) To(to ...interface{}) *MockMessage_To_Call {
	return &MockMessage_To_Call{Call: _e.mock.On("To",
		append([]interface{}{}, to...)...)}
}

func (_c *MockMessage_To_Call) Run(run func(to ...string)) *MockMessage_To_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		var variadicArgs []string
		if len(args) > 0 {
			variadicArgs = args[0].([]string)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockMessage_To_Call) Return(message contracts.Message) *MockMessage_To_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_To_Call) RunAndReturn(run func(to ...string) contracts.Message) *MockMessage_To_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockMessage
func (_mock *MockMessage) View(templateName string, data map[string]interface{}) contracts.Message {
	ret := _mock.Called(templateName, data)

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 contracts.Message
	if returnFunc, ok := ret.Get(0).(func(string, map[string]interface{}) contracts.Message); ok {
		r0 = returnFunc(templateName, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(contracts.Message)
		}
	}
	return r0
}

// MockMessage_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockMessage_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - templateName string
//   - data map[string]interface{}
func (_e *MockMessage_Expecter) View(templateName interface{}, data interface{}) *MockMessage_View_Call {
	return &MockMessage_View_Call{Call: _e.mock.On("View", templateName, data)}
}

func (_c *MockMessage_View_Call) Run(run func(templateName string, data map[string]interface{})) *MockMessage_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 map[string]interface{}
		if args[1] != nil {
			arg1 = args[1].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessage_View_Call) Return(message contracts.Message) *MockMessage_View_Call {
	_c.Call.Return(message)
	return _c
}

func (_c *MockMessage_View_Call) RunAndReturn(run func(templateName string, data map[string]interface{}) contracts.Message) *MockMessage_View_Call {
	_c.Call.Return(run)
	return _c
}
